spring:
  application:
    name: nexus
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:nexus}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        page-serialization-mode: via-dto
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
jwt:
  public:
    key: classpath:public.pem
  private:
    key: classpath:key.pem
