export enum EntityStatus {
  LOCKED = 'LOCKED',
  UNLOCKED = 'UNLOCKED',
  COMPLETED = 'COMPLETED'
}

export enum PlanetLabel {
  VARIABILI = 'VARIABILI',
  BIFURCA_9 = 'BIFURCA_9',
  CICLUS = 'CICLUS',
  MATRX_0 = 'MATRX_0'
}

export enum LevelLabel {
  ALUMINIUM_I = 'ALUMINIUM_I',
  ALUMINIUM_II = 'ALUMINIUM_II',
  ALUMINIUM_III = 'ALUMINIUM_III',
  IRON_I = 'IRON_I',
  IRON_II = 'IRON_II',
  IRON_III = 'IRON_III',
  NICKEL_I = 'NICKEL_I',
  NICKEL_II = 'NICKEL_II',
  NICKEL_III = 'NICKEL_III',
  PALLADIUM_I = 'PALLADIUM_I',
  PALLADIUM_II = 'PALLADIUM_II',
  PALLADIUM_III = 'PALLADIUM_III'
}