-- 1. Tabelas de Histórico e Execução
DROP TABLE IF EXISTS user_response CASCADE;
DROP TABLE IF EXISTS user_mission_attempt CASCADE;
DROP TABLE IF EXISTS user_mission CASCADE;
DROP TABLE IF EXISTS user_achievement CASCADE;

-- 2. Tabelas de Conteúdo e Recompensas
DROP TABLE IF EXISTS alternative CASCADE;
DROP TABLE IF EXISTS question CASCADE;
DROP TABLE IF EXISTS boss CASCADE;
DROP TABLE IF EXISTS achievement CASCADE;

-- 3. Tabelas Base de Conteúdo
DROP TABLE IF EXISTS mission CASCADE;

-- 4. Tabelas de Usuário e Stats
DROP TABLE IF EXISTS user_stat CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "level" CASCADE;

-- Levels
CREATE TABLE "level" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "number" int NOT NULL,
    xp_required int NOT NULL,
	CONSTRAINT pk_level PRIMARY KEY (id),
    CONSTRAINT ck_level_xp_required CHECK (xp_required >= 0)
);

-- Users
CREATE TABLE "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    "password" varchar(255) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uk_user_email UNIQUE(email)
);

-- User Stats
CREATE TABLE user_stat (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    level_id bigint NOT NULL,
    xp_current int DEFAULT 0 ,
    streak_current int DEFAULT 0,
    last_access timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_user_stat PRIMARY KEY (id),
    CONSTRAINT uk_user_stat_user UNIQUE (user_id),
    CONSTRAINT fk_user_stat_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_stat_level FOREIGN KEY(level_id) REFERENCES "level"(id) ON DELETE CASCADE,
    CONSTRAINT ck_user_stat_xp_current CHECK (xp_current >= 0),
    CONSTRAINT ck_user_stat_streak_current CHECK (streak_current >= 0)
);


-- 2. Mission & Content
CREATE TABLE mission (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title varchar(255) NOT NULL,
    description text,
    mission_prerequisite_id bigint REFERENCES mission(id),
    CONSTRAINT pk_mission PRIMARY KEY (id)
);

CREATE TABLE boss (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    mission_id bigint NOT NULL,
    "name" varchar(255) NOT NULL,
    description text,
    max_health int NOT NULL,
    CONSTRAINT pk_boss PRIMARY KEY (id),
    CONSTRAINT uk_boss_mission UNIQUE (mission_id),
    CONSTRAINT fk_boss_mission FOREIGN KEY(mission_id) REFERENCES mission(id) ON DELETE CASCADE,
    CONSTRAINT ck_boss_max_health CHECK (max_health > 0)
);

CREATE TABLE question (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    mission_id bigint NOT NULL,
    "statement" text NOT NULL,
    "order" int NOT NULL,
    CONSTRAINT pk_question PRIMARY KEY (id),
	CONSTRAINT uk_question_mission_order UNIQUE (mission_id, "order"),
    CONSTRAINT fk_question_mission FOREIGN KEY(mission_id) REFERENCES mission(id) ON DELETE CASCADE
);

CREATE TABLE alternative (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    question_id bigint NOT NULL,
    "content" text NOT NULL,
    is_correct boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_alternative PRIMARY KEY(id),
    CONSTRAINT fk_alternative_question FOREIGN KEY (question_id) REFERENCES question(id) ON DELETE CASCADE
);

-- 3. Execution & History
CREATE TABLE user_mission (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    mission_id bigint NOT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'IN_PROGRESS',
    best_result float,
    CONSTRAINT pk_user_mission PRIMARY KEY(id),
    CONSTRAINT uk_user_mission UNIQUE (user_id, mission_id),
    CONSTRAINT fk_user_mission_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_mission_mission FOREIGN KEY(mission_id) REFERENCES mission(id) ON DELETE CASCADE,
    CONSTRAINT ck_user_mission_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED'))
);

CREATE TABLE user_mission_attempt (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_mission_id bigint NOT NULL,
    start_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_at timestamp,
    is_boss_defeated boolean DEFAULT false,
    "result" float,
    CONSTRAINT pk_attempt PRIMARY KEY(id),
    CONSTRAINT fk_attempt_user_mission FOREIGN KEY (user_mission_id) REFERENCES user_mission(id) ON DELETE CASCADE
);

CREATE TABLE user_response (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    attempt_id bigint NOT NULL,
    alternative_id bigint NOT NULL,
    is_correct boolean NOT NULL,
    CONSTRAINT pk_user_response PRIMARY KEY(id),
    CONSTRAINT fk_user_response_attempt FOREIGN KEY (attempt_id) REFERENCES user_mission_attempt(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_response_alternative FOREIGN KEY (alternative_id) REFERENCES alternative(id) ON DELETE CASCADE 
);

-- 4. Achievements
CREATE TABLE achievement (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    description text,
    bonus_xp int DEFAULT 0,
    mission_id bigint,
    CONSTRAINT pk_achievement PRIMARY KEY(id),
    CONSTRAINT uk_achievement_mission UNIQUE (mission_id), 
    CONSTRAINT fk_achievement_mission FOREIGN KEY (mission_id) REFERENCES mission(id) ON DELETE CASCADE,
    CONSTRAINT ck_achievement_bonus_xp CHECK (bonus_xp >= 0)
);

CREATE TABLE user_achievement (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    achievement_id bigint NOT NULL,
    earned_at timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_achievement PRIMARY KEY(id),
    CONSTRAINT uk_user_achievement_pair UNIQUE (user_id, achievement_id), 
    CONSTRAINT fk_user_achievement_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_achievement_achievement FOREIGN KEY (achievement_id) REFERENCES achievement(id) ON DELETE CASCADE
);