-- ====================
-- DROPS
-- ====================
DROP TABLE IF EXISTS "user_resource" CASCADE;

DROP TABLE IF EXISTS "user_response" CASCADE;

DROP TABLE IF EXISTS "user_mission_attempt" CASCADE;

DROP TABLE IF EXISTS "user_mission" CASCADE;

DROP TABLE IF EXISTS "user_planet" CASCADE;

DROP TABLE IF EXISTS "alternative" CASCADE;

DROP TABLE IF EXISTS "question" CASCADE;

DROP TABLE IF EXISTS "resource" CASCADE;

DROP TABLE IF EXISTS "mission" CASCADE;

DROP TABLE IF EXISTS "planet" CASCADE;

DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS "level" CASCADE;

DROP DOMAIN IF EXISTS progress CASCADE;

DROP DOMAIN IF EXISTS score CASCADE;

DROP DOMAIN IF EXISTS oxygen CASCADE;

DROP DOMAIN IF EXISTS xp CASCADE;

DROP TYPE IF EXISTS entity_status CASCADE;

DROP TYPE IF EXISTS planet_label CASCADE;

DROP TYPE IF EXISTS level_label CASCADE;

-- ====================
-- TYPES
-- ====================
CREATE TYPE level_label AS ENUM (
    'ALUMINIUM_I',
    'ALUMINIUM_II',
    'ALUMINIUM_III',
    'IRON_I',
    'IRON_II',
    'IRON_III',
    'NICKEL_I',
    'NICKEL_II',
    'NICKEL_III',
    'PALLADIUM_I',
    'PALLADIUM_II',
    'PALLADIUM_III'
);

CREATE TYPE planet_label AS ENUM ('VARIABILI', 'BIFURCA_9', 'CICLUS', 'MATRX_0');

CREATE TYPE entity_status AS ENUM ('LOCKED', 'UNLOCKED', 'COMPLETED');

-- ====================
-- DOMAINS
-- ====================
CREATE DOMAIN xp bigint CHECK (VALUE >= 0);

CREATE DOMAIN oxygen int CHECK (VALUE BETWEEN 0 AND 10);

CREATE DOMAIN score DECIMAL(5, 2) CHECK (VALUE BETWEEN 0 AND 100);

-- ====================
-- LEVEL
-- ====================
CREATE TABLE
    "level" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "name" level_label NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        "xp_required" xp NOT NULL,
        CONSTRAINT pk_level PRIMARY KEY (id),
        CONSTRAINT uk_level_label UNIQUE ("name"),
        CONSTRAINT uk_level_order UNIQUE ("order")
    );

INSERT INTO
    "level" (
        "name",
        "description",
        "order",
        "xp_bonus",
        "xp_required"
    )
VALUES
    ('ALUMINIUM_I', NULL, 1, 0, 0),
    ('ALUMINIUM_II', NULL, 2, 10, 500);

-- ====================
-- USER
-- ====================
CREATE TABLE
    "user" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "username" varchar(255) NOT NULL,
        "email" varchar(255) NOT NULL,
        "password" varchar(255) NOT NULL,
        level_id bigint NOT NULL DEFAULT 1,
        "xp" xp NOT NULL DEFAULT 0,
        "oxygen" oxygen NOT NULL DEFAULT 10,
        CONSTRAINT pk_user PRIMARY KEY (id),
        CONSTRAINT fk_user_level FOREIGN KEY (level_id) REFERENCES "level" (id),
        CONSTRAINT uk_user_email UNIQUE ("email")
    );

-- ====================
-- PLANET
-- ====================
CREATE TABLE
    "planet" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "name" planet_label NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_planet PRIMARY KEY (id),
        CONSTRAINT uk_planet_name UNIQUE ("name"),
        CONSTRAINT uk_planet_order UNIQUE ("order")
    );

INSERT INTO
    "planet" ("name", "description", "order", "xp_bonus")
VALUES
    ('VARIABILI', NULL, 1, 10),
    ('BIFURCA_9', NULL, 2, 10);

CREATE TABLE
    "user_planet" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        planet_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        "is_current" boolean NOT NULL DEFAULT false,
        CONSTRAINT pk_user_planet PRIMARY KEY (id),
        CONSTRAINT fk_user_planet_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_planet_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_planet UNIQUE (user_id, planet_id)
    );

-- ====================
-- MISSION
-- ====================
CREATE TABLE
    "mission" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        planet_id bigint NOT NULL,
        "name" varchar(255) NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_mission PRIMARY KEY (id),
        CONSTRAINT fk_mission_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_mission_planet_name UNIQUE (planet_id, "name"),
        CONSTRAINT uk_mission_planet_order UNIQUE (planet_id, "order")
    );

INSERT INTO
    "mission" (
        planet_id,
        "name",
        "description",
        "order",
        "xp_bonus"
    )
VALUES
    (1, 'Planet - 1 : Mission - 1 ', NULL, 1, 10),
    (1, 'Planet - 1 : Mission - 2 ', NULL, 2, 10),
    (2, 'Planet - 2 : Mission - 3 ', NULL, 1, 10),
    (2, 'Planet - 2 : Mission - 1 ', NULL, 2, 10);

CREATE TABLE
    "user_mission" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        mission_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        "is_current" boolean NOT NULL DEFAULT false,
        "best_result" score NOT NULL DEFAULT 0,
        CONSTRAINT pk_user_mission PRIMARY KEY (id),
        CONSTRAINT fk_user_mission_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_mission_mission FOREIGN KEY (mission_id) REFERENCES "mission" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_mission UNIQUE (user_id, mission_id)
    );

CREATE TABLE
    "user_mission_attempt" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_mission_id bigint NOT NULL,
        "start_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "end_at" timestamp,
        "result" score NOT NULL DEFAULT 0,
        CONSTRAINT pk_attempt PRIMARY KEY (id),
        CONSTRAINT fk_attempt_user_mission FOREIGN KEY (user_mission_id) REFERENCES "user_mission" (id) ON DELETE CASCADE,
        CONSTRAINT ck_user_mission_attempt CHECK ("end_at" >= "start_at")
    );

-- ====================
-- QUESTION
-- ====================
CREATE TABLE
    "question" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        mission_id bigint NOT NULL,
        "name" varchar(50) NOT NULL,
        "description" text NOT NULL,
        "order" int NOT NULL,
        "code_snippet" text,
        CONSTRAINT pk_question PRIMARY KEY (id),
        CONSTRAINT fk_question_mission FOREIGN KEY (mission_id) REFERENCES "mission" (id) ON DELETE CASCADE,
        CONSTRAINT uk_question_mission_order UNIQUE (mission_id, "order")
    );

INSERT INTO
    "question" (
        mission_id,
        "name",
        "description",
        "order",
        "code_snippet"
    )
VALUES
    (1, 'Question 1', 'Mission 1 - Planet 1', 1, NULL),
    (1, 'Question 2', 'Mission 1 - Planet 1', 2, NULL),
    (2, 'Question 1', 'Mission 2 - Planet 1', 1, NULL),
    (2, 'Question 2', 'Mission 2 - Planet 1', 2, NULL),
    (3, 'Question 1', 'Mission 1 - Planet 2', 1, NULL),
    (3, 'Question 2', 'Mission 1 - Planet 2', 2, NULL),
    (4, 'Question 1', 'Mission 2 - Planet 2', 1, NULL),
    (4, 'Question 2', 'Mission 2 - Planet 2', 2, NULL);

CREATE TABLE
    "alternative" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        question_id bigint NOT NULL,
        "content" text NOT NULL,
        "feedback_tip" text NOT NULL,
        "is_correct" boolean NOT NULL DEFAULT false,
        CONSTRAINT pk_alternative PRIMARY KEY (id),
        CONSTRAINT fk_alternative_question FOREIGN KEY (question_id) REFERENCES "question" (id) ON DELETE CASCADE,
        CONSTRAINT uk_alternative_content UNIQUE (question_id, "content"),
        CONSTRAINT uk_alternative UNIQUE (question_id, id)
    );

INSERT INTO
    "alternative" (
        question_id,
        "content",
        "feedback_tip",
        "is_correct"
    )
VALUES
    -- Questão 1 - Missão 1 - Planet 1
    (
        1,
        'Content Alt 1 - Question 1 - Mission 1 - Planet 1',
        'Feedback Alt 1 - Question 1 - Mission 1 - Planet 1',
        true
    ),
    (
        1,
        'Content Alt 2 - Question 1 - Mission 1 - Planet 1',
        'Feedback Alt 2 - Question 1 - Mission 1 - Planet 1',
        false
    ),
    -- Questão 2 - Missão 1 - Planet 1
    (
        2,
        'Content Alt 1 - Question 2 - Mission 1 - Planet 1',
        'Feedback Alt 1 - Question 2 - Mission 1 - Planet 1',
        true
    ),
    (
        2,
        'Content Alt 2 - Question 2 - Mission 1 - Planet 1',
        'Feedback Alt 2 - Question 2 - Mission 1 - Planet 1',
        false
    ),
    -- Questão 1 - Missão 2 - Planet 1
    (
        3,
        'Content Alt 1 - Question 1 - Mission 2 - Planet 1',
        'Feedback Alt 1 - Question 1 - Mission 2 - Planet 1',
        true
    ),
    (
        3,
        'Content Alt 2 - Question 1 - Mission 2 - Planet 1',
        'Feedback Alt 2 - Question 1 - Mission 2 - Planet 1',
        false
    ),
    -- Questão 2 - Missão 2 - Planet 1
    (
        4,
        'Content Alt 1 - Question 2 - Mission 2 - Planet 1',
        'Feedback Alt 1 - Question 2 - Mission 2 - Planet 1',
        true
    ),
    (
        4,
        'Content Alt 2 - Question 2 - Mission 2 - Planet 1',
        'Feedback Alt 2 - Question 2 - Mission 2 - Planet 1',
        false
    ),
    -- Questão 1 - Missão 1 - Planet 2
    (
        5,
        'Content Alt 1 - Question 1 - Mission 1 - Planet 2',
        'Feedback Alt 1 - Question 1 - Mission 1 - Planet 2',
        true
    ),
    (
        5,
        'Content Alt 2 - Question 1 - Mission 1 - Planet 2',
        'Feedback Alt 2 - Question 1 - Mission 1 - Planet 2',
        false
    ),
    -- Questão 2 - Missão 1 - Planet 2
    (
        6,
        'Content Alt 1 - Question 2 - Mission 1 - Planet 2',
        'Feedback Alt 1 - Question 2 - Mission 1 - Planet 2',
        true
    ),
    (
        6,
        'Content Alt 2 - Question 2 - Mission 1 - Planet 2',
        'Feedback Alt 2 - Question 2 - Mission 1 - Planet 2',
        false
    ),
    -- Questão 1 - Missão 2 - Planet 2
    (
        7,
        'Content Alt 1 - Question 1 - Mission 2 - Planet 2',
        'Feedback Alt 1 - Question 1 - Mission 2 - Planet 2',
        true
    ),
    (
        7,
        'Content Alt 2 - Question 1 - Mission 2 - Planet 2',
        'Feedback Alt 2 - Question 1 - Mission 2 - Planet 2',
        false
    ),
    -- Questão 2 - Missão 2 - Planet 2
    (
        8,
        'Content Alt 1 - Question 2 - Mission 2 - Planet 2',
        'Feedback Alt 1 - Question 2 - Mission 2 - Planet 2',
        true
    ),
    (
        8,
        'Content Alt 2 - Question 2 - Mission 2 - Planet 2',
        'Feedback Alt 2 - Question 2 - Mission 2 - Planet 2',
        false
    );

CREATE TABLE
    "user_response" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        attempt_id bigint NOT NULL,
        question_id bigint NOT NULL,
        alternative_id bigint NOT NULL,
        CONSTRAINT pk_user_response PRIMARY KEY (id),
        CONSTRAINT fk_user_response_attempt FOREIGN KEY (attempt_id) REFERENCES "user_mission_attempt" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_response_question FOREIGN KEY (question_id) REFERENCES "question" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_response_alternative FOREIGN KEY (question_id, alternative_id) REFERENCES "alternative" (question_id, id) ON DELETE CASCADE,
        CONSTRAINT uk_user_response_question UNIQUE (attempt_id, question_id)
    );

-- ====================
-- RESOURCE
-- ====================
CREATE TABLE
    "resource" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        planet_id bigint NOT NULL,
        "name" varchar(255) NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_resource PRIMARY KEY (id),
        CONSTRAINT fk_resource_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_resource_name UNIQUE ("name"),
        CONSTRAINT uk_resource_order UNIQUE (planet_id, "order")
    );

INSERT INTO
    "resource" (
        planet_id,
        "name",
        "description",
        "order",
        "xp_bonus"
    )
VALUES
    (1, 'Planet - 1 : Resource', NULL, 1, 10),
    (2, 'Planet - 2 : Resource', NULL, 1, 10);

CREATE TABLE
    "user_resource" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        resource_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        CONSTRAINT pk_user_resource PRIMARY KEY (id),
        CONSTRAINT fk_user_resource_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_resource_resource FOREIGN KEY (resource_id) REFERENCES "resource" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_resource UNIQUE (user_id, resource_id)
    );