-- ====================
-- DROPS
-- ====================

DROP TABLE IF EXISTS "user_resource" CASCADE;
DROP TABLE IF EXISTS "user_response" CASCADE;
DROP TABLE IF EXISTS "user_mission_attempt" CASCADE;
DROP TABLE IF EXISTS "user_mission" CASCADE;
DROP TABLE IF EXISTS "user_achievement" CASCADE;

DROP TABLE IF EXISTS "alternative" CASCADE;
DROP TABLE IF EXISTS "question" CASCADE;
DROP TABLE IF EXISTS "resource" CASCADE;
DROP TABLE IF EXISTS "achivement_target" CASCADE;
DROP TABLE IF EXISTS "achievement" CASCADE;

DROP TABLE IF EXISTS "mission" CASCADE;
DROP TABLE IF EXISTS "planet" CASCADE;

DROP TABLE IF EXISTS "user_stat" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "level" CASCADE;


-- ====================
-- TYPES
-- ====================

CREATE TYPE difficulty_level 
    AS ENUM (
        'EASY', 
        'MEDIUM', 
        'HARD'
        );

CREATE TYPE mission_status 
    AS ENUM (
        'IN_PROGRESS', 
        'COMPLETED'
        );

CREATE TYPE achievement_scope 
    AS ENUM (
        'ENTITY', 
        'GAME'
        );

CREATE TYPE achievement_type 
    AS ENUM (
        'UNLOCK', 
        'COMPLETED', 
        'COLLECTED'
        );

CREATE TYPE entity_type 
    AS ENUM (
        'LEVEL', 
        'MISSION', 
        'PLANET'
        );


-- ====================
-- DOMAINS
-- ====================

CREATE DOMAIN score DECIMAL(5,2) CHECK (VALUE BETWEEN 0 AND 100);


-- ====================
-- LEVEL
-- ====================

CREATE TABLE "level" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    "number" int NOT NULL,
    "xp_required" int NOT NULL,
	
	CONSTRAINT pk_level PRIMARY KEY (id),
	
    CONSTRAINT uk_level_number UNIQUE("number"),
	
    CONSTRAINT ck_level_xp_required CHECK ("xp_required" >= 0)
);


-- ====================
-- USER
-- ====================

CREATE TABLE "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    "username" varchar(255) NOT NULL,
    "email" varchar(255) NOT NULL,
    "password" varchar(255) NOT NULL,
	
    CONSTRAINT pk_user PRIMARY KEY (id),
	
    CONSTRAINT uk_user_email UNIQUE("email")
);

CREATE TABLE "user_stat" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    level_id bigint NOT NULL,

    "xp_total" int DEFAULT 0 ,
    "streak_current" int DEFAULT 0,
    "last_access" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
    CONSTRAINT pk_user_stat PRIMARY KEY (id),
	
    CONSTRAINT fk_user_stat_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_stat_level FOREIGN KEY(level_id) REFERENCES "level"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_stat_user UNIQUE (user_id),
	
    CONSTRAINT ck_user_stat_xp_total CHECK ("xp_total" >= 0),
    CONSTRAINT ck_user_stat_streak_current CHECK ("streak_current" >= 0)
);


-- ====================
-- PLANET
-- ====================

CREATE TABLE "planet"(
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    "name" varchar(255) NOT NULL,
    "description" text,
    "order" int NOT NULL,
	
    CONSTRAINT pk_planet PRIMARY KEY (id),
	
    CONSTRAINT uk_planet_name UNIQUE("name"),
    CONSTRAINT uk_planet_order UNIQUE("order")
);


-- ====================
-- MISSION
-- ====================

CREATE TABLE "mission" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    planet_id bigint NOT NULL,

    "name" varchar(255) NOT NULL,
    "description" text,
    "order" int NOT NULL,
    "difficulty" difficulty_level NOT NULL,
	"xp_reward" int NOT NULL,
	
    CONSTRAINT pk_mission PRIMARY KEY (id),

    CONSTRAINT fk_mission_planet FOREIGN KEY(planet_id) REFERENCES "planet"(id) ON DELETE CASCADE,

    CONSTRAINT uk_mission_planet_name UNIQUE(planet_id, "name"),
    CONSTRAINT uk_mission_planet_order UNIQUE (planet_id, "order"),

	CONSTRAINT ck_mission_reward CHECK ("xp_reward" >= 0)
);

CREATE TABLE "user_mission" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    mission_id bigint NOT NULL,

    "status" mission_status NOT NULL DEFAULT 'IN_PROGRESS',
    "best_result" score NOT NULL DEFAULT 0,
	
    CONSTRAINT pk_user_mission PRIMARY KEY(id),
	
    CONSTRAINT fk_user_mission_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_mission_mission FOREIGN KEY(mission_id) REFERENCES "mission"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_mission UNIQUE (user_id, mission_id)
);

CREATE TABLE "user_mission_attempt" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_mission_id bigint NOT NULL,

    "start_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "end_at" timestamp,
    "result" score NOT NULL DEFAULT 0,

    CONSTRAINT pk_attempt PRIMARY KEY(id),

    CONSTRAINT fk_attempt_user_mission FOREIGN KEY (user_mission_id) REFERENCES "user_mission"(id) ON DELETE CASCADE,

    CONSTRAINT ck_user_mission_attempt CHECK ("end_at" >= "start_at")
);


-- ====================
-- QUESTION
-- ====================

CREATE TABLE "question" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    mission_id bigint NOT NULL,

    "description" text NOT NULL,
    "codeSnippet" text NOT NULL,
    "order" int NOT NULL,
	
    CONSTRAINT pk_question PRIMARY KEY (id),
	
    CONSTRAINT fk_question_mission FOREIGN KEY(mission_id) REFERENCES "mission"(id) ON DELETE CASCADE,

    CONSTRAINT uk_question_mission_order UNIQUE (mission_id, "order")
);

CREATE TABLE "alternative" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    question_id bigint NOT NULL,

    "content" text NOT NULL,
    "feedbackTip" text NOT NULL,
    "is_correct" boolean NOT NULL DEFAULT false,
	
    CONSTRAINT pk_alternative PRIMARY KEY(id),

    CONSTRAINT fk_alternative_question FOREIGN KEY (question_id) REFERENCES "question"(id) ON DELETE CASCADE,

	CONSTRAINT uk_alternative_content UNIQUE(question_id, "content"),
    CONSTRAINT uk_alternative UNIQUE (question_id, id)
);

CREATE TABLE "user_response" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    
    attempt_id bigint NOT NULL,
    question_id bigint NOT NULL,
    alternative_id bigint NOT NULL,
	
    CONSTRAINT pk_user_response PRIMARY KEY(id),
	
    CONSTRAINT fk_user_response_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES "user_mission_attempt"(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_response_question
        FOREIGN KEY (question_id)
        REFERENCES "question"(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_response_alternative
        FOREIGN KEY (question_id, alternative_id)
        REFERENCES "alternative"(question_id, id)
        ON DELETE CASCADE,

    CONSTRAINT uk_user_response_question
        UNIQUE(attempt_id, question_id)
);


-- ====================
-- RESOURCE
-- ====================

CREATE TABLE "resource" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    planet_id bigint NOT NULL,

    "name" varchar(255) NOT NULL,
    "description" text,
	
    CONSTRAINT pk_resource PRIMARY KEY (id),
	
    CONSTRAINT fk_resource_planet FOREIGN KEY(planet_id) REFERENCES "planet"(id) ON DELETE CASCADE,

    CONSTRAINT uk_resource_planet UNIQUE (planet_id),
    CONSTRAINT uk_resource_name UNIQUE ("name")
);

CREATE TABLE "user_resource" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    resource_id bigint NOT NULL,

    "collected_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	
    CONSTRAINT pk_user_resource PRIMARY KEY(id),
	
    CONSTRAINT fk_user_resource_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_resource_resource FOREIGN KEY(resource_id) REFERENCES "resource"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_resource UNIQUE (user_id, resource_id)
);


-- ====================
-- ACHIEVEMENT
-- ====================

CREATE TABLE "achievement" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    "name" varchar(255) NOT NULL,
    "description" text,
    "type" achievement_type NOT NULL,
    "scope" achievement_scope NOT NULL,
    "bonus_xp" int NOT NULL DEFAULT 0,
    
    CONSTRAINT pk_achievement PRIMARY KEY(id),

    CONSTRAINT ck_achievement_bonus_xp CHECK (bonus_xp >= 0)
);

CREATE TABLE "achievement_target" (
    achievement_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    
    "entity" entity_type NOT NULL,
    
    CONSTRAINT pk_achievement_target PRIMARY KEY (achievement_id, entity, entity_id),

    CONSTRAINT fk_achievement_target_achievement FOREIGN KEY(achievement_id) REFERENCES "achievement"(id) ON DELETE CASCADE
);

CREATE TABLE "user_achievement" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    achievement_id bigint NOT NULL,

    "collected_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	
    CONSTRAINT pk_user_achievement PRIMARY KEY(id),
	
    CONSTRAINT fk_user_achievement_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_achievement_achievement FOREIGN KEY (achievement_id) REFERENCES "achievement"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_achievement_pair UNIQUE (user_id, achievement_id)
);