spring:
  application:
    name: nexusrpg

  data:
    web:
      pageable:
        page-serialization-mode: via-dto

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexus}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: validate


app:
  cors:
    allowed-origins: "*"

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  public:
    key: classpath:public.pem
  private:
    key: classpath:key.pem
