spring:
  application:
    name: nexusrpg

  data:
    web:
      pageable:
        page-serialization-mode: via-dto

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origins: ${FRONTEND_URL}

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE