spring:
  application:
    name: nexusrpg

  data:
    web:
      pageable:
        page-serialization-mode: via-dto

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexus}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:3000}

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: projeto-integrador-extensionista-5-semestre-matutino-univag