-- ====================
-- DROPS
-- ====================
DROP TABLE IF EXISTS "user_response" CASCADE;

DROP TABLE IF EXISTS "user_mission_attempt" CASCADE;

DROP TABLE IF EXISTS "user_mission" CASCADE;

DROP TABLE IF EXISTS "user_planet" CASCADE;

DROP TABLE IF EXISTS "alternative" CASCADE;

DROP TABLE IF EXISTS "question" CASCADE;

DROP TABLE IF EXISTS "mission" CASCADE;

DROP TABLE IF EXISTS "planet" CASCADE;

DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS "level" CASCADE;

DROP DOMAIN IF EXISTS progress CASCADE;

DROP DOMAIN IF EXISTS score CASCADE;

DROP DOMAIN IF EXISTS oxygen CASCADE;

DROP DOMAIN IF EXISTS xp CASCADE;

DROP TYPE IF EXISTS entity_status CASCADE;

DROP TYPE IF EXISTS planet_label CASCADE;

DROP TYPE IF EXISTS level_label CASCADE;