-- ====================
-- LEVEL
-- ====================
CREATE TABLE
    "level" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "name" level_label NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        "xp_required" xp NOT NULL,
        CONSTRAINT pk_level PRIMARY KEY (id),
        CONSTRAINT uk_level_label UNIQUE ("name"),
        CONSTRAINT uk_level_order UNIQUE ("order")
    );

-- ====================
-- USER
-- ====================
CREATE TABLE
    "user" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "username" varchar(255) NOT NULL,
        "email" varchar(255) NOT NULL,
        "password" varchar(255) NOT NULL,
        level_id bigint NOT NULL DEFAULT 1,
        "xp" xp NOT NULL DEFAULT 0,
        "oxygen" oxygen NOT NULL DEFAULT 10,
        CONSTRAINT pk_user PRIMARY KEY (id),
        CONSTRAINT fk_user_level FOREIGN KEY (level_id) REFERENCES "level" (id),
        CONSTRAINT uk_user_email UNIQUE ("email")
    );

-- ====================
-- PLANET
-- ====================
CREATE TABLE
    "planet" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "name" planet_label NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_planet PRIMARY KEY (id),
        CONSTRAINT uk_planet_name UNIQUE ("name"),
        CONSTRAINT uk_planet_order UNIQUE ("order")
    );

CREATE TABLE
    "user_planet" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        planet_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        "is_current" boolean NOT NULL DEFAULT false,
        CONSTRAINT pk_user_planet PRIMARY KEY (id),
        CONSTRAINT fk_user_planet_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_planet_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_planet UNIQUE (user_id, planet_id)
    );

-- ====================
-- MISSION
-- ====================
CREATE TABLE
    "mission" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        planet_id bigint NOT NULL,
        "name" varchar(255) NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_mission PRIMARY KEY (id),
        CONSTRAINT fk_mission_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_mission_planet_name UNIQUE (planet_id, "name"),
        CONSTRAINT uk_mission_planet_order UNIQUE (planet_id, "order")
    );

CREATE TABLE
    "user_mission" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        mission_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        "is_current" boolean NOT NULL DEFAULT false,
        "best_result" score NOT NULL DEFAULT 0,
        CONSTRAINT pk_user_mission PRIMARY KEY (id),
        CONSTRAINT fk_user_mission_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_mission_mission FOREIGN KEY (mission_id) REFERENCES "mission" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_mission UNIQUE (user_id, mission_id)
    );

-- ====================
-- RESOURCE
-- ====================
CREATE TABLE
    "resource" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        planet_id bigint NOT NULL,
        "name" varchar(255) NOT NULL,
        "description" text,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_resource PRIMARY KEY (id),
        CONSTRAINT fk_resource_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_resource_name UNIQUE ("name"),
        CONSTRAINT uk_resource_order UNIQUE (planet_id, "order")
    );

CREATE TABLE
    "user_resource" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        resource_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        "is_current" boolean NOT NULL DEFAULT false,
        CONSTRAINT pk_user_resource PRIMARY KEY (id),
        CONSTRAINT fk_user_resource_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_resource_resource FOREIGN KEY (resource_id) REFERENCES "resource" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_resource UNIQUE (user_id, resource_id)
    );

-- ====================
-- QUESTION
-- ====================
CREATE TABLE
    "question" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        mission_id bigint NOT NULL,
        "content" text NOT NULL,
        "feedback" text NOT NULL,
        "order" int NOT NULL,
        CONSTRAINT pk_question PRIMARY KEY (id),
        CONSTRAINT fk_question_mission FOREIGN KEY (mission_id) REFERENCES "mission" (id) ON DELETE CASCADE,
        CONSTRAINT uk_question_mission_order UNIQUE (mission_id, "order")
    );

-- ====================
-- ALTERNATIVE
-- ====================
CREATE TABLE
    "alternative" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        question_id bigint NOT NULL,
        "content" text NOT NULL,
        "is_correct" boolean NOT NULL DEFAULT false,
        CONSTRAINT pk_alternative PRIMARY KEY (id),
        CONSTRAINT fk_alternative_question FOREIGN KEY (question_id) REFERENCES "question" (id) ON DELETE CASCADE,
        CONSTRAINT uk_alternative_content UNIQUE (question_id, "content")
    );

-- ====================
-- ATTEMPT
-- ====================
CREATE TABLE
    "attempt" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_mission_id bigint NOT NULL,
        "start_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "end_at" timestamp,
        "result" score NOT NULL DEFAULT 0,
        CONSTRAINT pk_attempt PRIMARY KEY (id),
        CONSTRAINT fk_attempt_user_mission FOREIGN KEY (user_mission_id) REFERENCES "user_mission" (id) ON DELETE CASCADE,
        CONSTRAINT ck_user_mission_attempt CHECK ("end_at" >= "start_at")
    );

-- ====================
-- RESPONSE
-- ====================
CREATE TABLE
    "response" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        attempt_id bigint NOT NULL,
        question_id bigint NOT NULL,
        alternative_id bigint NOT NULL,
        CONSTRAINT pk_user_response PRIMARY KEY (id),
        CONSTRAINT fk_user_response_attempt FOREIGN KEY (attempt_id) REFERENCES "attempt" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_response_question FOREIGN KEY (question_id) REFERENCES "question" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_response_alternative FOREIGN KEY (alternative_id) REFERENCES "alternative" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_response UNIQUE (attempt_id, question_id)
    );